version: '3.8'

services:
  mapping-service:
    image: vitalie97/mapping-service-backend:v1.0.2
    ports:
      - "8095:8095"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095"]
      interval: 30s
      timeout: 10s
      retries: 5

  initializer:
    image: vitalie97/mapping-service-initializer:v1.0.2
    depends_on:
      mapping-service:
        condition: service_healthy

  frontend:
    image: vitalie97/mapping-service-frontend:v1.0.2
    ports:
      - "80:80"
