version: '3.8'

services:
  mapping-service:
    image: vitalie97/mapping-service-backend:v.1.0.3
    ports:
      - "8095:8095"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

  initializer:
    #image: vitalie97/mapping-service-initializer:v.1.0.3
    build: ./initializer
    depends_on:
      mapping-service:
        condition: service_healthy

  frontend:
    image: vitalie97/mapping-service-frontend:v1.0.3
    ports:
      - "${MAPPING_FRONTPORT:-80}:80"
    depends_on:
      mapping-service:
        condition: service_healthy
