version: '3.8'

services:
  mapping-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/plugins:/mapping-service/plugins
      - ./backend/mappingSchemas:/mapping-service/mappingSchemas
    ports:
      - "8095:8095"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095"]
      interval: 30s
      timeout: 10s
      retries: 5

  initializer:
    build:
      context: ./initializer
      dockerfile: Dockerfile
    depends_on:
      mapping-service:
        condition: service_healthy
    volumes:
      - ./backend/mappingSchemas:/mapping-service/mappingSchemas

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      mapping-service:
        condition: service_healthy